spring.application.name=turismo-api

# Configuração do Banco de Dados MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/descubra_paulista?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=34449127

# Estratégia do Hibernate (Cria/Atualiza as tabelas de segurança e novas entidades automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Chave secreta usada pelo TokenService para criptografar o JWT
api.security.token.secret=ChaveSuperSecretaDoDescubraPaulista2026